### ISSUE TITLE
 SERVLET:org.apache.felix.http.base.internal.dispatch.DispatcherServlet-4ad56128

### ISSUE THREAD

**Issue by FrancoStino** [ciechanowiec/dock_aem#2]
Hi, 
i have this issue. How can i resolve it?

Sorry for making a video but I wanted to show you if the procedure is right or am I doing something wrong?

Java: Oracle JDK 11.0.22
AEM Cloud: AEM SDK v2024.2.15262.20240224T002940Z-231200

[Video del 14-03-2024 21:45:50.webm](https://github.com/ciechanowiec/dock_aem/assets/32127923/c3159a80-3151-4eda-b917-13481eb78a40)

**Comment by sabdouni** [comment]
I am facing the same issue on my side, when shutting down an aem instance using docker stop.
The segment store gets missed out, and on the next start aem can't find the zip.
I tried starting aem using tini, to avoid having running threads when i stop aem, still the same issue

**Comment by sabdouni** [comment]
@FrancoStino,
Try adding stop_grace_period: 300s to the docker-compose, to give more time to the JVM to shutdown gracefully.
Otherwise, docker will wait 10s than kill the JVM

And also add the following lines to aem-starter.sh

```
terminate() {
    echo "Stopping AEM..."
    # Insert the command to stop AEM gracefully
    /opt/aem/crx-quickstart/bin/stop
    echo "AEM stopped gracefully."
    exit 0
}

# Trap SIGTERM and SIGINT to call the terminate function
trap terminate SIGTERM SIGINT
```

**Comment by ciechanowiec** [comment]
@FrancoStino, @sabdouni, the root cause of the problems you encountered might be related to rapid shutdowns of the AEM application during image build and container run. I introduced some changes so that now the AEM application in both mentioned cases is shut down gracefully. You can find the changes in the latest version of the code on the master branch: https://github.com/ciechanowiec/dock_aem/commit/795c900a25d21b2c8ebd64a0fdcfd4e38051c474. Could you please try one more time with this latest version?

**Comment by FrancoStino** [comment]
> @FrancoStino, @sabdouni, the root cause of the problems you encountered might be related to rapid shutdowns of the AEM application during image build and container run. I introduced some changes so that now the AEM application in both mentioned cases is shut down gracefully. You can find the changes in the latest version of the code on the master branch: [795c900](https://github.com/ciechanowiec/dock_aem/commit/795c900a25d21b2c8ebd64a0fdcfd4e38051c474). Could you please try one more time with this latest version?

Hi @ciechanowiec,
thanks for the support. It works I am sending you attached the screens of successful build.

![Schermata del 2024-05-06 11-34-16](https://github.com/ciechanowiec/dock_aem/assets/32127923/daa6bfd8-cf1f-427c-ba05-36680544cf9c)
![Schermata del 2024-05-06 11-34-36](https://github.com/ciechanowiec/dock_aem/assets/32127923/bacae308-c99a-42b9-83d9-f27e6305cfe9)


Thank you so much!
